#!/usr/bin/env php
<?php

foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
    if (file_exists($file)) {
        require $file;
        break;
    }
}

$factory = new \JoRo\ReversePath();

$deploymentNames = $factory->getDeploymentNames();
if (empty($deploymentNames)) {
    exit("\033[31mNo deployment configuration found!\033[0m" . PHP_EOL);
}

if (isset($argv[1])) {
    if (in_array($argv[1], $deploymentNames, true)) {
        $deploymentName = $argv[1];
    } else {
        echo "\033[31mConfiguration '" . $argv[1] . "' not found! Using first configuration...\033[0m" . PHP_EOL;
        $deploymentName = $deploymentNames[0];
    }
} else {
    $deploymentName = $deploymentNames[0];
}

$includeDeployment = $factory->getDeploymentsBasePath() . '/' . $deploymentName . ".php";

if (is_file($includeDeployment)) {
    echo "\033[32mStarting reverse deployment '" . $deploymentName . "' ...\033[0m" . PHP_EOL;
    include_once($includeDeployment);
} else {
    exit("\033[31mThis is not a file ...\033[0m" . PHP_EOL);
}
