#!/usr/bin/env php
<?php

foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
    if (file_exists($file)) {
        /** @noinspection PhpIncludeInspection */
        require $file;
        break;
    }
}

use JoRo\ReversePath;
use TYPO3\Flow\Utility\Files;

$factory = new \JoRo\ReversePath();

if(isset($argv[1]) && in_array($argv[1],$factory->getDeploymentNames())) {
    $deploymentName = $argv[1];
} else {
    $deploymentName = $factory->getDeploymentNames()[0];
}

$includeDeployment = $factory->getDeploymentsBasePath() . '/' . $deploymentName . ".php";

if(is_file($includeDeployment)) {
    echo "\033[32mStarting reverse deployment '" . $deploymentName . "' ...\033[0m" . PHP_EOL;
    include_once($includeDeployment);
} else {
    exit("\033[31mThis is not a file ...\033[0m" . PHP_EOL);
}