#!/usr/bin/env php
<?php

foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
    if (file_exists($file)) {
        /** @noinspection PhpIncludeInspection */
        require $file;
        break;
    }
}

use JoRo\ReversePath;
use TYPO3\Flow\Utility\Files;

$factory = new \JoRo\ReversePath();

print_r($factory->getDeploymentsBasePath());
echo PHP_EOL;
print_r($factory->getDeploymentNames());
echo PHP_EOL;